name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GRADLE_CACHE_KEY: ${{ github.run_id }}-gradle-${{ github.run_number }}-${{ github.run_number }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.GRADLE_CACHE_KEY }}
        restore-keys: ${{ env.GRADLE_CACHE_KEY }}
    - name: Run tests
      run: chmod +x gradlew && ./gradlew test

